
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";

export const FETCH_CHAPTER_READ = "FETCH_CHAPTER_READ";
export const FETCH_BOOK_CHAPTER_READ = "FETCH_BOOK_CHAPTER_READ";
