
export const FETCH_USER = "FETCH_USER";
export const FETCH_GROUP_FEED = "FETCH_GROUP_FEED";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";

export const FETCH_CHAPTER_READ = "FETCH_CHAPTER_READ";
export const FETCH_BOOK_CHAPTER_READ = "FETCH_BOOK_CHAPTER_READ";

export const BOOK_COMPLETE = "BOOK_COMPLETE";
export const CONFIRM_GROUP_JOIN = "CONFIRM_GROUP_JOIN";
export const FAILED_GROUP_JOIN = "FAILED_GROUP_JOIN";
