export const WITTY_LOADER = [
  'rendering new mercies',
  'awaiting the second coming',
  'deleting anxiousness',
  'examinging the heart',
  'praying for an extra byte',
  'choosing filters for verses',
  'waiting for appointed time',
  'decrypting utterances',
  'electing database',
  'seeking kingdom 1.0',
  'lifting praise v1.0',
  'watching dispensationalism and covenant debates',
  'polishing memory verses',
  'purchasing sunday coffee',
  'filling database with holy spirit',
  'accurately handling webpages',
  'considering bible version',
  'humming holy tunes',
  'forming digital womb',
  'clapping hands',
  'downvoting the prodigal son',
  'removing stumbling blocks',
  'casting the second stone',
  'preparing triumphal data entry',
  'bribing tax collector',
  'sending out the 12 bytes',
  'burning a CD sacrifice',
  'deleting old self',
  'listening to a sermon',
  'thinking of hashtags',
  'scolding lost lamb',
  'pruning vines',
  'aligning out of context posts',
  'checking commentaries',
  'asking a seminary student',
  'growing a beard',
  'wearing a cardigan',
  'listening to a dating series',
  'waiting in the doughnut line',
  'looking for a parking space',
  'surfing babylon bee',
  'flipping through the bible',
  'planting seeds for the fruits of the spirit',
  'burning wicked chaffs',
  'hebrewsing coffee',
  'do you Noah guy?',
]
